import Header from "@/components/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.scss";
import Footer from "@/components/Footer";
import { ViewportContextProvider } from "@/context/viewport.context";
import { CartStoreProvider } from "@/stores/cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ViewportContextProvider>
          <CartStoreProvider>
            <Header />
            <main className="main">{children}</main>
            <Footer />
          </CartStoreProvider>
        </ViewportContextProvider>
      </body>
    </html>
  );
}
